hailey_quinn_dict = {
    "Nice to meet you": "Omg i love new friend.",
    "Love your perfume": "I love your perfume. What is it? The stench of death?",
    "woman": "Every woman has a crazy side that only the right man can bring out.",
    "Were you just thinking": "What, were you just... thinking you can have a happy family and coach a little league, and pay the car? Normal is a setting on the dryer. People like us, we don't become normal!",
    "Harley": "Harley is back, bitches.",
    "bad": "We are bad, that's what we do.",
    "Who are you": "I am Harley Quinn. I have twice the intelligence of Batman and all the vitamins in a bowl of oranges.",
    "tell about you": "Welcome everyone to the greatest show on earth. My name is Harleen Quinzel but my friends and enemies know me as Harley Quinn, and I will be your host tonight.",
    "My rational mind can recognize pain": "My rational mind can recognize pain when it sees it. But my irrational mind is a very small box. Packed and with a bow on top.",
    "Legend movie guy": "That's the guy from the movie 'Legend'! I love that movie! Will there be unicorns too?",
    "How are my babies": "How are my babies? Do any of you have more ammo for mom?",
    "five second": "If I'm not out of here in five seconds, someone's going to have their kidneys removed. Yeah, you heard right, no kidneys. Without kidneys!",
    "Who likes Batman": "Of course! So, who is he? Who likes Batman? An old love, a criminal, a nun, Robin?",
    "Power of girls": "Yeah yeah yeah, the power of girls! I hate having to say this to strong female characters, but I'm just a side show.",
    "Incite chaos and destruction": "I will incite chaos and destruction wherever I go.",
    "joker sure": "Yes, yes, he knew that none of them were the real Mr. Joker. But she had to be sure.",
    "Caliph of clowns": "Look closely, wage slaves! Presenting the caliph of clowns, the mogul of charlatans. The only and irreplaceable, the Joker!",
    "Harley bat": "Harley Quinn with a bat",
    "Put on these glasses": "Here you go! Just put on these glasses and change your costume and no one will know you're the same person.",
    "Ivy know you think": "Ivy, I know you think I like this guy, but you're just going to end up tied to that rocket.",
    "What the hell is this costume": "What the hell? This costume! Are you, the president of my fan club?",
    "No he doesn't like me": "No, he doesn't like me...",
    "How the world works": "I know how the world works, okay? And when it comes to the heart, they're all out for themselves, right?",
    "Found the Joker's mind disturbing": "I found the Joker's mind disturbing, his madness alarming, and his charm irresistible! What can I say? The boy did it for me.",
    "For what it's worth": "You know, for what it's worth, I really enjoyed some of our games, but there comes a time when a girl wants more. And now, all this girl wants is to settle down with her beloved.",
    "Hey Grifter": "Hey, Grifter! Didn't anyone tell you you're supposed to escape from prison, not get into it, idiot?",
    "Their intentions are for the good": "Not everyone understands that their intentions are for the good of the whole world. I am her best friend.",
    "So unromantic": "That was so unromantic.",
    "i think": "You think I'm just a doll you can make any way you want. You're wrong. Very wrong. What you think of me is just a ghost in time. I am dangerous and I will show you how dark I can be.",
    "I'm not in the mood": "Listen, I'm not in the mood for this nonsense. Especially after the day I've had.",
    "Wouldn't it be fun if": "Wouldn't it be fun if they just held hands and started kissing?",
    "Bruce Wayne": "Bruce Wayne, your millionaire ass is so mine.",
    "Why can't a girl be nice": "Why can't a girl be nice to a guy without him trying to tease her?",
    "Harley Quinn smiling": "Harley Quinn smiling.",
    "what": "And that's when everything fell apart.",
    "i made a mistake": "Believe me, if anyone knows him, it's me. He was the biggest mistake of your entire life. Don't let that be yours.",
    "Question. Would you die for me?" :"Yes.",
    "That's too easy. Will you... Would you live for me? ... Hmm?":"Yes.",
    "Careful! Do not say this oath thoughtlessly! ... Desire becomes surrender, surrender becomes power. You want this?":"I do.",
    "Say it. Say it. Say it! Pretty, pretty, pretty, pretty, pretty, pretty, pretty...":"Please?!",
    "Mm, God, you're so... good!" : "..."
}
